config/routes.rb
Rails.application.routes.draw do
  resources :inventories
  devise_for :stores,controllers: {registrations: "stores/registrations", sessions: "stores/sessions", confirmations: "stores/confirmations", passwords: "stores/passwords"}
  resources :books
  get '/sell' => 'stores#sell', as: "sell"
  post '/do_sell' => 'stores#do_sell'
  post '/addcopies' => 'stores#addcopies'
   root 'stores#index'
  get '/dashboard' => 'stores#dashboard', as: "dashboard"

end

app/models/book.rb
class Book < ActiveRecord::Base
has_many :book_invs
has_many :inventories, :through  => :book_invs

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  def mapping(book)
    b=BookInv.new
    b.book_id=book.id
    b.inventory_id= current_store.inventory.id
    b.copies=0
    b.save
  end

  # POST /books.json
  def create
    @book = Book.new(book_params)
    respond_to do |format|
      if @book.save
        mapping(@book)
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
   params.require(:book).permit(:title, :publisher, :edition, :price, :author_name)

    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<div class="row center" style="padding: 40px">
<div class="col s12"><%= form_for(@book) do |f| %>

  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row center">
<div class="input-field col s6 field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
    </div>

 <div class="input-field col s6 field">
    <%= f.label :author_name%><br>
    <%= f.text_field :author_name %>
  </div>
  </div>
  <div class="row center">
<div class="input-field col s12 field">
    <%= f.label :publisher %><br>
    <%= f.text_field :publisher %>
  </div>
  </div>
  <div class="row center">
 <div class="input-field col s12 field">
    <%= f.label :edition %><br>
    <%= f.number_field :edition %>
  </div>
  </div>
  <div class="row center">
 <div class="input-field col s12 field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  </div>

  <div class="actions">
    <a class="waves-effect waves-light btn-large"><%= f.submit %></a>
  </div>
<% end %>
</div>
</div>

app/views/books/edit.html.erb
<%= render 'form' %>



<div class="random ">
<div class="waves-effect waves-light btn"><%= link_to 'Show', @book %></div>
<div class="waves-effect waves-light btn"><%= link_to 'Back' , dashboard_path %></div>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Publisher</th>
      <th>Edition</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.publisher %></td>
        <td><%= book.edition %></td>
        <td><%= book.author_name %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<%= render 'form' %>

app/views/books/show.html.erb
<div style="padding:40px; display:flex; flex-direction: column; align-items: center;">

<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @book.publisher %>
</p>

<p>
  <strong>Edition:</strong>
  <%= @book.edition %>
</p>

<p>
  <strong>Author:</strong>

  <%= @book.author_name%>
</p>

<div class="random ">
<div class="waves-effect waves-light btn"><%= link_to 'Edit', edit_book_path(@book) %></div>
<div class="waves-effect waves-light btn"><%= link_to 'Back' , dashboard_path %></div>
</div>
</div>