config/routes.rb
Rails.application.routes.draw do
  resources :inventories
  devise_for :stores,controllers: {registrations: "stores/registrations", sessions: "stores/sessions", confirmations: "stores/confirmations", passwords: "stores/passwords"}
  resources :books
  get '/sell' => 'stores#sell', as: "sell"
  post '/do_sell' => 'stores#do_sell'
  post '/addcopies' => 'stores#addcopies'
   root 'stores#index'
  get '/dashboard' => 'stores#dashboard', as: "dashboard"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookInventory</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>

  <%= csrf_meta_tags %>
</head>
<body>



<nav>
    <div class="nav-wrapper header">

   			<a href="/" class="brand-logo">BOOK INVENTORY</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><% if current_store.nil? %>
                    <a href="/">Home</a>

            <% else %>
                <a href="/dashboard">Home</a>
            <%end %>
          </li>
        <li> <% if store_signed_in? %>
		<%= link_to 'Signout', destroy_store_session_path, method: "Delete" %>
        <% else %>
        <%= link_to 'Signin' , new_store_session_path %>
        <% end %>
       </li>
       <li>
       	<%= link_to 'New Store Registration', new_store_registration_path %>
       </li>
      </ul>
    </div>
  </nav>
  <br/>
  <br/>
  <br/>
  <br/>

  <p class="notice"><%= notice %> </p>
  <p class="alert"><%= alert %> </p>


<div class="wide-container #e3f2fd blue lighten-5" style="height: 100%, width: 100%">

<%= yield %>

</div>

</body>
</html>